version: "3.8"

services:

  mongo:
    image: mongo:5.0
    ports:
      - "27018:27017"
    volumes:
      - ~/apps/mongo:/data/database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoADVS
      - MONGO_INITDB_ROOT_PASSWORD=mongoADVS
    command: mongod --quiet --logpath /dev/null

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "2345:2342"
    command: --port 2342

  web:
    build: .
    container_name: telegram_ADVS
    command: bash -c 'python main.py'
    volumes:
      - .:/code
    network_mode: host
    env_file:
      - .env
