version: "3.10"

services:

  mongodb:
    image: mongo:5.0
    container_name: mongoADVS
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoADVS
      - MONGO_INITDB_ROOT_PASSWORD=mongoADVS
    command: mongod --quiet --logpath /dev/null

  redis:
    image: redis:alpine
    container_name: redisADVS
    ports:
      - "2342:2342"
    command: --port 2342

  web:
    build: .
    container_name: telegram_bot
    command: bash -c 'python main.py'
    volumes:
      - .:/code
    depends_on:
      - mongodb
    network_mode: host
    env_file:
      - .env